[project]
name = "multi-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.1.1",
    "docx2txt>=0.9",
    "faiss-cpu>=1.12.0",
    "ipykernel>=6.30.1",
    "langchain>=0.3.27",
    "langchain-astradb>=0.6.1",
    "langchain-community>=0.3.31",
    "langchain-core>=0.3.78",
    "langchain-experimental>=0.3.4",
    "langchain-groq>=0.3.8",
    "langchain-huggingface>=0.3.1",
    "langchain-openai>=0.3.35",
    "langchain-pinecone>=0.2.12",
    "langchain-text-splitters>=0.3.11",
    "numpy>=2.3.3",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "pinecone>=7.3.0",
    "pymupdf>=1.26.4",
    "pypdf>=6.1.1",
    "python-docx>=1.2.0",
    "python-dotenv>=1.1.1",
    "rank-bm25>=0.2.2",
    "sentence-transformers>=5.1.1",
    "tiktoken>=0.12.0",
    "torch>=2.8.0",
    "transformers>=4.57.0",
    "unstructured>=0.18.15",
]
